name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish_interface_lib:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Simple.Schedule.Job.Interfaces/Simple.Schedule.Job.Interfaces.csproj
          PACKAGE_NAME: Simple.Schedule.Job.Interfaces
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
  publish_core_lib:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Simple.Schedule.Job/Simple.Schedule.Job.csproj
          PACKAGE_NAME: Simple.Schedule.Job
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}